#!/usr/bin/env python3
"""
Dataset completeness & accuracy audit — run AFTER collect_refresh.py + collect_misc_backfill.py.

For every season 2021-2026 it rebuilds the game universe fresh from LeagueGameLog, then verifies:
  1. Coverage: every game has pbp (repo or refresh), misc (refresh), advanced (refresh)
  2. 2023 repair: zero team-games with 0 paint points (480/520 were broken pre-repair)
  3. Box identity: FTM + 3*FG3M + 2*(FGM-FG3M) == PTS on every team gamelog row
  4. Channel sanity: non-paint 2s >= 0 for every team-game with misc data
  5. Cross-source accuracy vs Drive masters (2021-Jul 2025 overlap):
     team PTS vs master_team_cleaned; team paint sums vs master_player (2023 excluded: repaired)
  6. Odds coverage per season from data/drive_masters/master_odds.csv
  7. Duplicates + V2/V3 schema census

Outputs: data/refresh_2026/AUDIT_REPORT.md, data/refresh_2026/missing_artifacts.csv
"""
import json
from pathlib import Path

import pandas as pd

from collect_refresh import get_gamelog

OUT = Path("data/refresh_2026")
SEASONS = ["2021", "2022", "2023", "2024", "2025", "2026"]
TYPES = ["Regular Season", "Playoffs"]

lines, problems = [], []

def note(s=""):
    print(s); lines.append(s)

def team_gamelogs():
    """Fresh team gamelog per season+type from the API (the authoritative game universe)."""
    frames = []
    for season in SEASONS:
        for st in TYPES:
            t = get_gamelog(season, st, "T")
            if len(t):
                t["season"], t["season_type"] = season, st
                frames.append(t)
    return pd.concat(frames, ignore_index=True)

def main():
    note("# Dataset completeness & accuracy audit")
    note(f"\nGenerated by audit_completeness.py")

    tg = team_gamelogs()
    tg["GAME_ID"] = tg.GAME_ID.astype(str)
    universe = tg.groupby(["season", "GAME_ID"]).size().reset_index()[["season", "GAME_ID"]]

    have_pbp_repo = {p.stem.split("_")[1] for p in Path("data/playbyplay").glob("pbp_*.parquet")}
    have_pbp_new = {p.stem.split("_")[1] for p in (OUT / "pbp").glob("pbp_*.parquet")}
    have_misc = {p.stem.split("_")[1] for p in (OUT / "misc").glob("misc_*.parquet")}
    have_adv = {p.stem.split("_")[1] for p in (OUT / "advanced").glob("advanced_*.parquet")}

    # 1 -- coverage table
    note("\n## 1. Per-season artifact coverage")
    note("\n| season | games | pbp | misc | advanced |")
    note("|---|---|---|---|---|")
    missing_rows = []
    for season, grp in universe.groupby("season"):
        ids = set(grp.GAME_ID)
        pbp_ok = ids & (have_pbp_repo | have_pbp_new)
        misc_ok = ids & have_misc
        adv_ok = ids & have_adv
        note(f"| {season} | {len(ids)} | {len(pbp_ok)} | {len(misc_ok)} | {len(adv_ok)} |")
        for gid in sorted(ids):
            miss = [k for k, s in [("pbp", have_pbp_repo | have_pbp_new), ("misc", have_misc), ("advanced", have_adv)] if gid not in s]
            if miss:
                missing_rows.append({"season": season, "GAME_ID": gid, "missing": "+".join(miss)})
    pd.DataFrame(missing_rows).to_csv(OUT / "missing_artifacts.csv", index=False)
    note(f"\nGames missing any artifact: **{len(set(r['GAME_ID'] for r in missing_rows))}** (detail: missing_artifacts.csv)")
    if missing_rows:
        problems.append(f"{len(set(r['GAME_ID'] for r in missing_rows))} games missing artifacts")

    # helper: team-level paint sums from misc files
    def team_paint(gids):
        recs = []
        for gid in gids:
            f = OUT / "misc" / f"misc_{gid}.parquet"
            if not f.exists():
                continue
            d = pd.read_parquet(f)
            pcol = "pointsPaint" if "pointsPaint" in d.columns else "PTS_PAINT"
            tcol = "teamId" if "teamId" in d.columns else "TEAM_ID"
            gcol = "gameId" if "gameId" in d.columns else "GAME_ID"
            s = d.groupby(tcol)[pcol].sum(min_count=1).reset_index()
            s.columns = ["TEAM_ID", "paint"]
            s["GAME_ID"] = str(d[gcol].iloc[0]).zfill(10)
            recs.append(s)
        return pd.concat(recs, ignore_index=True) if recs else pd.DataFrame(columns=["TEAM_ID", "paint", "GAME_ID"])

    # 2 -- 2023 paint repair
    note("\n## 2. 2023 misc repair (paint must never be 0)")
    ids23 = sorted(universe[universe.season == "2023"].GAME_ID)
    p23 = team_paint(ids23)
    zero23 = int((p23.paint.fillna(0) <= 0).sum())
    note(f"\n2023 team-games with paint data: {len(p23)} | zero/absent paint: **{zero23}** (was 480/520 pre-repair; must be 0)")
    if zero23:
        problems.append(f"2023 paint still broken in {zero23} team-games")

    # 3 -- box identity on the fresh team gamelogs
    note("\n## 3. Box-score identity (FTM + 3x3PM + 2x(FGM-3PM) == PTS)")
    viol = tg[(tg.FTM + 3 * tg.FG3M + 2 * (tg.FGM - tg.FG3M) - tg.PTS).abs() > 0]
    note(f"\nViolations: **{len(viol)}** of {len(tg)} team-game rows")
    if len(viol):
        problems.append(f"{len(viol)} box-identity violations")

    # 4 -- non-paint 2s >= 0 everywhere we have misc
    note("\n## 4. Channel sanity: non-paint 2-pt points >= 0")
    allpaint = team_paint(sorted(universe.GAME_ID))
    m = tg.merge(allpaint, on=["GAME_ID", "TEAM_ID"], how="inner")
    m["np2"] = 2 * (m.FGM - m.FG3M) - m.paint
    neg = m[m.np2 < 0]
    note(f"\nTeam-games checked: {len(m)} | negative non-paint-2s: **{len(neg)}**")
    if len(neg):
        problems.append(f"{len(neg)} negative non-paint-2s team-games")
        neg[["season", "GAME_ID", "TEAM_ID", "paint", "np2"]].to_csv(OUT / "negative_np2.csv", index=False)

    # 5 -- cross-source accuracy vs Drive masters
    note("\n## 5. Cross-source accuracy vs July-15 Drive masters")
    dm = Path("data/drive_masters")
    if (dm / "master_team_cleaned.csv").exists():
        old = pd.read_csv(dm / "master_team_cleaned.csv", low_memory=False)
        old["GAME_ID"] = old.GAME_ID.astype(str).str.zfill(10)
        j = tg.merge(old[["GAME_ID", "TEAM_ID", "team_pts"]], on=["GAME_ID", "TEAM_ID"], how="inner")
        bad = j[(j.PTS - j.team_pts).abs() > 0]
        note(f"\nTeam PTS vs master_team_cleaned: {len(j)} overlapping team-games, **{len(bad)}** mismatches")
        if len(bad):
            problems.append(f"{len(bad)} PTS mismatches vs old team master")
    if (dm / "master_player.csv").exists():
        oldp = pd.read_csv(dm / "master_player.csv", low_memory=False)
        if "player_pts_paint" in oldp.columns:
            oldp["GAME_ID"] = oldp.GAME_ID.astype(str).str.zfill(10)
            oldpaint = oldp.groupby(["GAME_ID", "TEAM_ID"]).player_pts_paint.sum(min_count=1).reset_index()
            j2 = allpaint.merge(oldpaint, on=["GAME_ID", "TEAM_ID"], how="inner")
            j2 = j2[~j2.GAME_ID.str.startswith(("1022300", "1042300"))]  # 2023 was broken in old master
            j2 = j2.dropna(subset=["player_pts_paint"])
            bad2 = j2[(j2.paint - j2.player_pts_paint).abs() > 0]
            note(f"Team paint vs master_player (2023 excluded): {len(j2)} comparable team-games, **{len(bad2)}** mismatches")
            if len(bad2):
                problems.append(f"{len(bad2)} paint mismatches vs old player master")
                bad2.to_csv(OUT / "paint_mismatches.csv", index=False)

    # 6 -- odds coverage
    note("\n## 6. Odds coverage (master_odds.csv)")
    if (dm / "master_odds.csv").exists():
        odds = pd.read_csv(dm / "master_odds.csv", low_memory=False)
        odds = odds.dropna(subset=["game_id"])
        odds["GAME_ID"] = odds.game_id.astype("int64").astype(str).str.zfill(10)
        note("\n| season | games in universe | games with odds | coverage |")
        note("|---|---|---|---|")
        for season, grp in universe.groupby("season"):
            ids = set(grp.GAME_ID)
            got = len(ids & set(odds.GAME_ID))
            note(f"| {season} | {len(ids)} | {got} | {got/len(ids)*100:.0f}% |")
        note("\n(2021 = 0% and 2026 = 0% are known permanent/pending gaps; capture decision with John.)")

    # 7 -- duplicates + schema census
    note("\n## 7. Duplicates & schema census")
    dup_u = universe.GAME_ID.duplicated().sum()
    v2_new = sum(1 for p in (OUT / "pbp").glob("pbp_*.parquet") if "GAME_ID" in pd.read_parquet(p, columns=None).columns[:3])
    note(f"\nDuplicate game ids in universe: {dup_u}")
    note(f"V2-schema files inside refresh pbp folder (should be 0 after refetch): {v2_new}")
    note(f"Legacy V2 pbp files in data/playbyplay: {len(have_pbp_repo)} (expected 996)")
    if v2_new:
        problems.append(f"{v2_new} V2-schema files still in refresh pbp folder")

    # verdict
    note("\n## Verdict")
    if problems:
        note("\n**NOT CLEAN — issues found:**")
        for p in problems:
            note(f"- {p}")
    else:
        note("\n**CLEAN — every check passed.** Dataset certified complete for 2021-2026 to date.")

    (OUT / "AUDIT_REPORT.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"\nReport written to {OUT/'AUDIT_REPORT.md'}")

if __name__ == "__main__":
    main()
