@echo off
rem AUTO-GENERATED by ops_hide_task_windows_noadmin.ps1 -- do not edit by hand.
rem Original action for scheduled task: WNBA prospective pair
rem Restore the task with:  ops_hide_task_windows_noadmin.ps1 -Undo
cd /d "C:\Users\jgallagher\wnba-betting-model"
"C:\Users\jgallagher\wnba-betting-model\prospective_pair\run_pair.cmd"
exit /b %ERRORLEVEL%
