@echo off
rem AUTO-GENERATED by ops_hide_task_windows_noadmin.ps1 -- do not edit by hand.
rem Original action for scheduled task: WNBA_PropsCapture_1
rem Restore the task with:  ops_hide_task_windows_noadmin.ps1 -Undo
"C:\Users\jgallagher\AppData\Local\Programs\Python\Python313\python.exe" "C:\Users\jgallagher\wnba-betting-model\props_capture_daily.py"
exit /b %ERRORLEVEL%
