@echo off
rem AUTO-GENERATED by ops_hide_task_windows_noadmin.ps1 -- do not edit by hand.
rem Original action for scheduled task: WNBA_ReplyDeliveryWatchdog
rem Restore the task with:  ops_hide_task_windows_noadmin.ps1 -Undo
"powershell.exe" -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "C:\Users\jgallagher\OneDrive - Sasserath Co\WNBA\supervisor_claude\reply_delivery_watchdog.ps1"
exit /b %ERRORLEVEL%
