@echo off
rem Matches the pattern generated by ops_hide_task_windows_noadmin.ps1 -- the task
rem invokes run_hidden.vbs against this file so no console window appears.
rem Original action for scheduled task: WNBA_LineupCapture
"C:\Users\jgallagher\wnba-betting-model\lineup_capture_tick.cmd"
exit /b %ERRORLEVEL%
