@echo off
rem AUTO-GENERATED by ops_hide_task_windows_noadmin.ps1 -- do not edit by hand.
rem Original action for scheduled task: WNBA_DailyForecast_PM
rem Restore the task with:  ops_hide_task_windows_noadmin.ps1 -Undo
"C:\Users\jgallagher\AppData\Local\Programs\Python\Python313\python.exe" "C:\Users\jgallagher\wnba-betting-model\daily_forecast.py" --live
exit /b %ERRORLEVEL%
