@echo off
rem AUTO-GENERATED by ops_hide_task_windows_noadmin.ps1 -- do not edit by hand.
rem Original action for scheduled task: WNBA_RefAssignments
rem Restore the task with:  ops_hide_task_windows_noadmin.ps1 -Undo
cd /d "C:\Users\jgallagher\wnba-betting-model"
"C:\Users\jgallagher\AppData\Local\Programs\Python\Python313\python.exe" "C:\Users\jgallagher\wnba-betting-model\ref_assignments_capture_daily.py"
exit /b %ERRORLEVEL%
