@echo off
rem AUTO-GENERATED by ops_hide_task_windows_noadmin.ps1 -- do not edit by hand.
rem Original action for scheduled task: WNBA_InjuryLive
rem Restore the task with:  ops_hide_task_windows_noadmin.ps1 -Undo
"C:\Users\jgallagher\wnba-betting-model\injury_live_tick.cmd"
exit /b %ERRORLEVEL%
